Feature/wbdsbla 3707 angular web worker ablosen
weisenburger/angular-web-worker pull request #1
Opened 2023-08-10 08:49 UTC by michaelkopf

2023-08-11 09:29 UTC, thomasrenger requested changes

2023-08-11 09:29 UTC, thomasrenger commented on package.json
> +    "build:schematics": "npm run remove:schematics && tsc -p src/schematics/tsconfig.schematics.json && npm run move:schematics",
Wollten wir löschen

2023-08-11 09:29 UTC, thomasrenger commented on tsconfig.lib.json
> +    // "files": ["AUTOGENERATED"]
Hier mal bitte prüfen

2023-08-15 06:13 UTC, michaelkopf commented on tsconfig.lib.json
> +    // "files": ["AUTOGENERATED"]
removed

2023-08-15 06:13 UTC, michaelkopf commented on package.json
> +    "build:schematics": "npm run remove:schematics && tsc -p src/schematics/tsconfig.schematics.json && npm run move:schematics",
ist gelöscht

2023-08-15 10:06 UTC, thomasrenger approved these changes

2023-08-15 12:37 UTC, merged